# Generated by Django 6.0.4 on 2026-05-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingProfile',
        ),
    ]
