# setup/settings/base.py
"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import dj_database_url
import environ
env = environ.Env()
environ.Env.read_env('.env')

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR  'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
HOSTS=env('HOSTS').split(',')
DOMAIN=HOSTS[0]
AUTH_USER_MODEL = 'accounts.User'

ALLOWED_HOSTS = HOSTS
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in HOSTS] + \
    [f'http://{host}' for host in HOSTS]

INSTALLED_APPS = [
    'setup',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'django_filters',
    'formtools',

    'accounts',
    'billing',
    'djstripe',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.discord',

    'feed',
    'karma',
    'notifications',
    'tasks',

    'procrastinate.contrib.django',
]

SITE_ID = 1
AUTHENTICATION_BACKENDS = ['allauth.account.auth_backends.AuthenticationBackend']

ACCOUNT_SIGNUP_FIELDS = []
SOCIALACCOUNT_ONLY = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_LOGIN_ON_GET = True

ACCOUNT_ADAPTER = 'accounts.account_adapter.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.SocialAccountAdapter'

ACCOUNT_EMAIL_VERIFICATION = 'none'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Respect reverse-proxy scheme/host (e.g., Tailscale Funnel) so OAuth callbacks
# are built with https:// when the public edge terminates TLS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'servestatic.middleware.ServeStaticMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'accounts.middleware.RequireUsernameMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'setup.honeypot.HoneypotMiddleware',               # after messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'setup' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.navbar_karma',
                'setup.context_processors.ads',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}')
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'setup' / 'static' / 'manual']
STATIC_ROOT = BASE_DIR / 'setup' / 'static' / 'cache'
STATICFILES_STORAGE = 'servestatic.storage.CompressedManifestStaticFilesStorage'

# Messages: store in signed cookie so near-miss redirects don't bloat the session.
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'


GITHUB_ERROR_REPO = env('GITHUB_ERROR_REPO', default='Vic-Nas/KarmaRace')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        # Suppress duplicate log records with identical (logger, level, message).
        # Useful for warnings that fire once per worker process on startup.
        'dedup': {
            '()': 'setup.log_filters.DedupFilter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['dedup'],
        },
        'github': {
            'level': 'ERROR',
            'class': 'setup.github_logging.GitHubIssueHandler',
        },
    },
    'root': {
        'handlers': ['console', 'github'],
        'level': 'INFO',
    },
    'loggers': {
        # Procrastinate registers tasks at INFO on every worker boot; mostly noise.
        # WARNING still surfaces real problems (failed jobs, connector errors).
        'procrastinate': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Honeypot scanner hits are DEBUG-only; don't pollute WARNING stream.
        # setup.honeypot propagates to setup.honeypot.middleware naturally.
        'setup.honeypot': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Gunicorn worker boot lines (Started server process, Waiting for
        # application startup, etc.) are too verbose with 8 workers; one
        # summary line per boot is enough. ERROR still surfaces real crashes.
        'gunicorn.error': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # py.warnings captures Python warnings module output (e.g.
        # StreamingHttpResponse sync iterator warning). Dedup filter on the
        # console handler above already collapses per-worker repeats.
        'py.warnings': {
            'handlers': ['console'],
            'propagate': False,
        },
    },
}
