# Generated by Django 6.0.4 on 2026-05-01 01:36
# accounts/migrations/0002_outreachcontactedemail_outreachdailystats_and_more.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachContactedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('queued_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('pending_after', models.IntegerField(default=0)),
                ('harvested', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='outreachrecord',
            name='accounts_ou_state_ba8e66_idx',
        ),
        migrations.AddField(
            model_name='outreachrecord',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='outreachrecord',
            index=models.Index(fields=['-score'], name='accounts_ou_score_e45714_idx'),
        ),
        migrations.RemoveField(
            model_name='outreachrecord',
            name='state',
        ),
    ]
