# Generated by Django 6.0.4 on 2026-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('producthunt', 'Product Hunt')], max_length=50),
        ),
    ]
