# Generated by Django 6.0.4 on 2026-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedaccount',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('discord', 'Discord')], max_length=50),
        ),
    ]
