# Generated by Django 6.0.4 on 2026-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_outreachcontactedemail_outreachdailystats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccount',
            name='discord_notifs_thread_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
