# Generated by Django 6.0.4 on 2026-05-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_outreachmonthlystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_offset', models.IntegerField(default=0)),
                ('harvest_lang', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outreach State',
            },
        ),
        migrations.DeleteModel(
            name='OutreachDailyStats',
        ),
        migrations.DeleteModel(
            name='OutreachMonthlyStats',
        ),
    ]
