# Generated by Django 6.0.4 on 2026-04-26 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GITHUB_STAR', 'Github Star'), ('GITHUB_FORK', 'Github Fork'), ('WEBHOOK', 'Webhook')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField()),
                ('target_id', models.CharField(max_length=500)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('karma_reward', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('succeed_count', models.PositiveIntegerField(default=0)),
                ('tried_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('owner_unpublished', models.BooleanField(default=False)),
                ('health_failure_streak', models.PositiveSmallIntegerField(default=0)),
                ('health_last_failure_reason', models.TextField(blank=True, default='')),
                ('health_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_health_success_count', models.PositiveIntegerField(default=0)),
                ('webhook_health_failure_count', models.PositiveIntegerField(default=0)),
                ('health_last_result', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ManyToManyField(blank=True, related_name='archived_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReciprocityObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('GITHUB_STAR', 'Github Star'), ('GITHUB_FORK', 'Github Fork'), ('WEBHOOK', 'Webhook')], max_length=20)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('FULFILLED', 'Fulfilled')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_due', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_owed', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations_fulfilled', to='tasks.task')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations_created', to='tasks.task')),
            ],
            options={
                'indexes': [models.Index(fields=['debtor', 'state'], name='tasks_recip_debtor__9207fd_idx'), models.Index(fields=['debtor', 'creditor', 'task_type', 'state'], name='tasks_recip_debtor__a6bcb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('result_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'tester')},
            },
        ),
    ]
