# Generated by Django 6.0.4 on 2026-05-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='karma_reward',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='reward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
