# Generated by Django 6.0.4 on 2026-04-17 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciprocityObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('GITHUB_STAR', 'Github Star'), ('GITHUB_FORK', 'Github Fork'), ('PH_COMMENT', 'Ph Comment'), ('WEBHOOK', 'Webhook')], max_length=20)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('FULFILLED', 'Fulfilled')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_due', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_owed', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations_fulfilled', to='tasks.task')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations_created', to='tasks.task')),
            ],
            options={
                'indexes': [models.Index(fields=['debtor', 'state'], name='tasks_recip_debtor__9207fd_idx'), models.Index(fields=['debtor', 'creditor', 'task_type', 'state'], name='tasks_recip_debtor__a6bcb3_idx')],
            },
        ),
    ]
