# Generated by Django 6.0.4 on 2026-04-19 19:21

from django.db import migrations, models
from django.utils.text import slugify


def backfill_task_slugs(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all().order_by('id'):
        if task.slug:
            continue

        base = slugify(task.description or task.target_id or task.type or 'task')
        base = (base or 'task')[:160]
        candidate = base
        idx = 2
        while Task.objects.exclude(pk=task.pk).filter(owner_id=task.owner_id, slug=candidate).exists():
            suffix = f'-{idx}'
            candidate = f'{base[:160-len(suffix)]}{suffix}'
            idx += 1

        task.slug = candidate
        task.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_health_last_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.RunPython(backfill_task_slugs, migrations.RunPython.noop),
    ]
