# Generated by Django 6.0.4 on 2026-05-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_karma_reward_taskcompletion_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciprocityobligation',
            name='error_strike_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reciprocityobligation',
            name='source_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reciprocityobligation',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12),
        ),
    ]
