# Generated by Django 6.0.4 on 2026-05-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_reciprocityobligation_error_strike_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='webhook_health_failure_count',
        ),
        migrations.RemoveField(
            model_name='task',
            name='webhook_health_success_count',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='result_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
