# Generated by Django 6.0.4 on 2026-05-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_webhook_health_failure_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reciprocityobligation',
            name='tasks_recip_debtor__9207fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='reciprocityobligation',
            name='tasks_recip_debtor__a6bcb3_idx',
        ),
        migrations.DeleteModel(
            name='ReciprocityObligation',
        ),
    ]
