# Generated by Django 6.0.4 on 2026-04-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_health_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
