# Generated by Django 6.0.4 on 2026-04-18 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('TASK_EARNED', 'Task Earned'), ('TASK_COST', 'Task Cost'), ('FLAG_UP_SENT', 'Flag Up Sent'), ('FLAG_UP_RECEIVED', 'Flag Up Received')], max_length=20)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
