# Generated by Django 6.0.4 on 2026-05-02 15:29
# karma/migrations/0002_alter_karmatransaction_reason.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmatransaction',
            name='reason',
            field=models.CharField(choices=[('TASK_EARNED', 'Task Earned'), ('TASK_COST', 'Task Cost'), ('FLAG_UP_SENT', 'Flag Up Sent'), ('FLAG_UP_RECEIVED', 'Flag Up Received'), ('STAFF_ADJUSTMENT', 'Staff Adjustment')], max_length=30),
        ),
    ]
