# Generated by Django 6.0.4 on 2026-04-17 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('TASK_COMPLETED', 'Task Completed'), ('KARMA_CHANGED', 'Karma Changed'), ('PROJECT_STATE', 'Project State'), ('APPRECIATION', 'Appreciation'), ('PROMISE_ACCEPTED', 'Promise Accepted'), ('PROMISE_BREACHED', 'Promise Breached'), ('FLAG_UP_RECEIVED', 'Flag Up Received'), ('TASK_HEALTH_FAILED', 'Task Health Failed')], max_length=30)),
                ('payload', models.JSONField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('TASK_COMPLETED', 'Task Completed'), ('KARMA_CHANGED', 'Karma Changed'), ('PROJECT_STATE', 'Project State'), ('APPRECIATION', 'Appreciation'), ('PROMISE_ACCEPTED', 'Promise Accepted'), ('PROMISE_BREACHED', 'Promise Breached'), ('FLAG_UP_RECEIVED', 'Flag Up Received'), ('TASK_HEALTH_FAILED', 'Task Health Failed')], max_length=30)),
                ('email_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook')], max_length=10)),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationpreference')),
            ],
        ),
    ]
