# Generated by Django 6.0.4 on 2026-05-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('TASK_CONFIRMED', 'Task Confirmed'), ('TASK_HEALTH_FAILED', 'Task Health Failed'), ('WEBHOOK_CHECK', 'Webhook Check'), ('KARMA_LOW', 'Karma Low'), ('KARMA_RESTORED', 'Karma Restored'), ('KARMA_ADJUSTED', 'Karma Adjusted'), ('PROJECT_STATE', 'Project State'), ('APPRECIATION', 'Appreciation'), ('FLAG_UP_RECEIVED', 'Flag Up Received'), ('FLAG_UP_SENT', 'Flag Up Sent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event',
            field=models.CharField(choices=[('TASK_CONFIRMED', 'Task Confirmed'), ('TASK_HEALTH_FAILED', 'Task Health Failed'), ('WEBHOOK_CHECK', 'Webhook Check'), ('KARMA_LOW', 'Karma Low'), ('KARMA_RESTORED', 'Karma Restored'), ('KARMA_ADJUSTED', 'Karma Adjusted'), ('PROJECT_STATE', 'Project State'), ('APPRECIATION', 'Appreciation'), ('FLAG_UP_RECEIVED', 'Flag Up Received'), ('FLAG_UP_SENT', 'Flag Up Sent')], max_length=30),
        ),
    ]
