# Generated by Django 6.0.4 on 2026-04-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='discord_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook'), ('DISCORD', 'Discord')], max_length=10),
        ),
    ]
