# Generated by Django 6.0.4 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreference_discord_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_enabled',
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('WEBHOOK', 'Webhook'), ('DISCORD', 'Discord')], max_length=10),
        ),
    ]
